# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


variables:
  - name: azureSubscription
    value: 'Visual Studio Enterprise Subscription(1)(8a492d1a-7c52-4257-a559-a0787afd1321)'

trigger:
- main

stages:
- stage: Build
  displayName: Build and Publish
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script:
        npm install
      displayName: 'Install Angular dependencies'
    
    - script: |
        apt-get update
        apt-get install google-chrome-stable
      displayName: 'Install Google Chrome for tests'
    
     - script: 
        npm run test-single-run
      displayName: 'Run Tests'
    
    # Cleanup step to terminate any remaining processes
    - script: |
        pkill chrome
      displayName: 'Cleanup Test Environment'

    - script:
        npm run build --prod
      displayName: 'Build Angular app'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/nba-tracking-app'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifactName: 'drop'
    
- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy to Azure Web App
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy'
            inputs:
              azureSubscription: 'Visual Studio Enterprise Subscription(1)(8a492d1a-7c52-4257-a559-a0787afd1321)'
              appType: 'webAppLinux'
              appName: 'nba-tracking-app'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'